-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
--
-- Creates the `feedback` table backing the anonymous "How are we doing?" prompt shown to
-- visitors on the opportunities page (see api/submit-feedback.js), and immediately locks
-- it down the same way waitlist/contact_messages are (see lockdown.sql): the public anon
-- key never gets any privilege on this table, so the service-role-only, rate-limited
-- endpoint is the only way a row is ever written. No email or name column at all — the
-- prompt is deliberately anonymous ("no email required, just a note").
--
-- Safe to re-run — IF NOT EXISTS / REVOKE-of-nothing / re-adding an existing constraint
-- with a different name / ENABLE-twice are all no-ops or cheap no-op-equivalents.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  rating text,
  note text,
  created_at timestamptz not null default now()
);

revoke all on public.feedback from anon, authenticated;
alter table public.feedback enable row level security;

alter table public.feedback
  add constraint feedback_rating_allowed
  check (rating is null or rating in ('very-bad', 'bad', 'okay', 'good', 'great'));

alter table public.feedback
  add constraint feedback_note_length check (note is null or length(note) <= 2000);

-- at least one of rating/note must be present — matches the API's own validation, as a
-- database-level backstop in case anything ever inserts a row without going through it
alter table public.feedback
  add constraint feedback_not_empty
  check (rating is not null or (note is not null and length(trim(note)) > 0));
